### ISSUE TITLE
Issue # 1 - WRSPM

### ISSUE THREAD

**Issue by wildweasel02** [wildweasel02/CSC325-Group-Project#1]
According to the [brightspace page](https://mylearning.suny.edu/d2l/le/content/445830/viewContent/15050835/View), we must complete the WRSPM. 
It says it must be detailed and it should include the world assumptions, user requirements, specifications (and interface needs), program, and hardware.

**Comment by wildweasel02** [comment]
Maybe some world assumptions could include (this is a very, VERY rough sketch of my ideas at this point, but will probably change): 
- users are interacting from all over the world
- users have an internet connection (is it safe to assume this? maybe not, but is it? what do you think? ... )
- the devices used by users have the processing power to handle requests 
- I assume some people who use the system will have conditions that deviate from the average, such as color-blindness 
- should we assume that most people have a browser? or access to the Play Store?
- people have different levels of technical skills, some may navigate better than others

Do y'all think this is ok for some world assumptions? maybe too general?

**Comment by AnaSal023** [comment]
One requirement with all WRSPM elements:
W- Assuming all users have an email address that they will use to sign up for the application. 
R - The user wants to sign in with their email address. 
S - The system must enter the user’s email address in an input field. 
P - HTML and Java will code the input text field, allowing the user to enter text into the user interface/GUI.
M - The user’s phone/computer will show the UI/GUI.
Eh – Email address (not entered)
Ev – Enter email address
Sv – Input text field
Sh – Data stored in the system

**Comment by wildweasel02** [comment]
for the "R" section of the WRSPM, I would also like to add, in addition to what was said above: 
- the user wants to be able able to text with other online users 
- the user wants to be able to add friends 
- the user wants to receive messages in real-time
- the user wants to hold private conversations with only certain other users

**Comment by wildweasel02** [comment]
for the "S" section of the WRSPM, I would like to add, in addition to what was said above:
- the system shall create a secure account for the user using the user's email, password, and date of birth
- all users shall be 16 years old or older
- the password of the user must be at least 8 characters
- users can make "friends" by sending friend requests to other users, which the receiving user can either accept or decline. 
- privacy should be ensured by following standards and using secure data transfers. 
(to be continued and edited)

**Comment by wildweasel02** [comment]
for the "M" section of the WRSPM, I would also like to add, in addition to what was said above:
- if the app is web-based, the app will run in the browser. If the app is for android mobile devices, it will run on android smartphones supporting at least Android 5.0, which is compatible with about 99% of Android devices. Once again, this is after we settle if we web-based or mobile-based in the other issue.

**Comment by wildweasel02** [comment]
>  Eh – Email address (not entered) 
>  Ev – Enter email address 
>  Sv – Input text field 
Also, @AnaSal023 , in addition to the topics you mentioned, I think Eh can also include other personal user information like their date of birth and pictures, up until they become Ev when they choose the information to put into our app, similar to pictures. When they upload a profile picture, it becomes Ev. Also, Sv can also include buttons, textviews, and prompts for the user.

**Comment by AnaSal023** [comment]
> > Eh – Email address (not entered)
> > Ev – Enter email address
> > Sv – Input text field
> 
> Also, @AnaSal023 , in addition to the topics you mentioned, I think Eh can also include other personal user information like their date of birth and pictures, up until they become Ev when they choose the information to put into our app, similar to pictures. When they upload a profile picture, it becomes Ev. Also, Sv can also include buttons, textviews, and prompts for the user.

Should we made a separate wrspm for the profile picture. Something like:
W- Assuming all users have a picture they want to use as their profile picture.
R - The user wants to add their picture to be shown on their profile.
S - The system must take the user’s picture and add it to be shown on their profile.
P - HTML and Java will code the image and add it to the user’s profile information. 
M - The user’s phone/computer will show the picture in the UI/GUI.
Eh – User’s picture (not posted)
Ev – User’s picture (posted as their profile picture)
Sv – User’s image
Sh – Image stored in the system

**Comment by wildweasel02** [comment]
> Should we made a separate wrspm for the profile picture

Hmmm I didn't think of that. I thought we will group all the Ws, Rs, Ss, Ps, and Ms together. Your idea is an interesting take. Sure, I think we can do it.

**Comment by AnaSal023** [comment]
4.	Add/search user to friend list
W – Assuming the user’s friend has an account on the chat application.
R – The user wants to add them to their friend list
S – The systems will take the user’s username/email into an input text field to search for their profile in the database and allow the user to add them as their friend.
P – MongoDB will confirm if the username/email exists in the chat app database, Java and HTML will create the input text field, search button, and will notify the user if the other user exists in the database, if it exists it will add them to their friend’s list.
M – User’s machine (device) will access the database, run the program, and display the UI/GUI.
Eh – Username/email (not entered)
Ev – Username/email (entered in the input text field)
Sv – Search button, message if the user doesn’t exist, prompt notifying the user that a new contact has been added to their friend’s list.
Sh – Usernames/email list in the database

**Comment by AnaSal023** [comment]
> > Should we made a separate wrspm for the profile picture
> 
> @AnaSal023 Hmmm I didn't think of that. I thought we will group all the Ws, Rs, Ss, Ps, and Ms together. Your idea is an interesting take. Sure, I think we can do it.

@wildweasel02 Oh! I was thinking of doing each WRSPM separately like adding them to a list or a table

**Comment by SilverCyclon** [comment]
Workflow: Workflow refers to the ease and efficiency of completing tasks within the app. In the context of a chat app, this could include how easy it is to sign up, find friends, and start chatting.

Reliability: Reliability refers to the app's ability to perform consistently and without errors. For a chat app, this could include ensuring that messages are sent and received promptly and that the app doesn't crash or freeze.

Security: Security refers to the app's ability to protect user data and prevent unauthorized access. In the case of a chat app, this could include implementing encryption for messages and using secure authentication methods.

Performance: Performance refers to the app's speed and efficiency. In a chat app, this could include ensuring that messages are sent and received quickly, and that the app runs smoothly even with multiple users.

Maintainability: Maintainability refers to the ease of maintaining and updating the app. This could include using modular code structures, commenting your code, and choosing easy-to-maintain libraries and frameworks.

**Comment by wildweasel02** [comment]
Hi all @AnaSal023 @sungwoo-parkk @TimothyArchbold @SilverCyclon , I created a google document so we can put all of the final ideas of the WRSPM in there and then save it as a word doc for final submission. [Here is the link](https://docs.google.com/document/d/1CCflFntvtXZNns4jQDpCWjtvCB5ubDiiV0-4NPKgd-k/edit?usp=sharing). Let me know if you can access it. You should be able to write on it and make changes. I would really like all of us to work on it.

**Comment by wildweasel02** [comment]
@SilverCyclon, from my understanding of the concept, WRSPM stands for world assumptions, requirements, specification, program, and machine.
