### ISSUE TITLE
Working on the capstone project porposal idea - Issue 

### ISSUE THREAD

**Issue by wildweasel02** [wildweasel02/CSC325-Group-Project#2]
Hi all ! According to brightspace instructions, we need to "describe the idea of your capstone project" in 2 or 3 paragraphs. 
Do y'all have any propositions?

**Comment by wildweasel02** [comment]
Here is what I think, since most of us agreed on a chat app: 

"There will be multiple users in the systems. Users will be able to interact simultaneously with the system and communicate with each other. Before that, the user needs to log in and add some details about themselves to create their profile. The user also needs to accept some conditions before finalizing the account. 

Once in, users can make friends and add them to their friend list. They can create private group chats or stay on the main. They can communicate through their keyboard and share pictures and other information that they want. There will be a report option for other users to report users who violated the agreed upon conditions."

What do y'all think? Good? Bad? Meh? This can all be just communication to help us draw out the final proposal.

**Comment by AnaSal023** [comment]
We can also say that the users can add a profile picture.

**Comment by SilverCyclon** [comment]
Seems pretty legit to me, not too elaborate though.

**Comment by wildweasel02** [comment]
@SilverCyclon do you want to elaborate?

**Comment by SilverCyclon** [comment]
I meant we shouldnt over complicate it
