### ISSUE TITLE
Web-based or mobile-based application

### ISSUE THREAD

**Issue by AnaSal023** [wildweasel02/CSC325-Group-Project#3]
We need to decide whether the application will be a web-based or mobile-based application.
Leave your opinions, resources, or anything that will help us decide

**Comment by wildweasel02** [comment]
I would be more inclined to choose the mobile application (for Android devices). 
For the majority of the population, it makes more sense for user to use a mobile app to chat with others as opposed to logging into a browser. The amount of people who use whatsapp, messenger, viber, line (etc...) as a mobile app as opposed to logging into a browser is much higher. 
I am new to Android development, but I am very excited for it, more than if we were to do the project web-based. I want to hear what you think too.

**Comment by wildweasel02** [comment]
I am willing to learn how to do both and don't want to close myself to anything in particular. However, for this project, I do agree that we will have to choose either one or the other.

**Comment by wildweasel02** [comment]
I will have to do more research and get back to this issue. this is important to figure out.

**Comment by SilverCyclon** [comment]
Im sort-of leaning towards web.....

**Comment by AnaSal023** [comment]
I'll say to make a mobile-based application. It will be easier from what I see online
